---
packages:
  - fail2ban
  - tmux
  - git
  - unattended-upgrades

users_to_add:
  - user: deploy             
    github: jacobLandefjall 
  - user: deploy
    github: kamhaal
  - user: deploy
    github: vinkeln

server_user: deploy