---
-   name: Remove subnet
    azure.azcollection.azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        virtual_network: "microblog-Vnet"
        name: "microblog-Subnet"
        state: absent


-   name: Remove virtual network
    azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "microblog-Vnet"
        state: absent
