---
- import_playbook: terminate_instances.yml    # Resta servers
- import_playbook: provision_instances.yml    # Create servers
- import_playbook: gather_instances.yml       # Get server IP
- import_playbook: security_groups.yml        # Create security groups
- import_playbook: 10-first-minutes.yml       # Run SSH hardening and basic setup
