---
- name: Terminate Azure instances
  hosts: local
  connection: local
  gather_facts: False

  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Terminate instances
      include_role:
        name: terminate_instances