---
#-   name: Set root password
    #user:
       # name: root
        #password: "{{ root_password | password_hash('sha512') }}"

-   name: Update apt-cache and upgrade
    apt:
        force_apt_get: yes
        update_cache: yes
        cache_valid_time: 3600
        upgrade: yes
    ignore_errors: yes

-   name: Install packages
    apt:
        force_apt_get: yes
        name: "{{ packages }}"

-   name: Copy unattended upgrades 10 settings
    copy:
        mode: "644"
        src: files/apt_periodic
        dest: /etc/apt/apt.conf.d/10periodic

-   name: Copy unattended upgrades 50 settings
    copy:
        mode: "644"
        src: files/apt_periodic_50
        dest: /etc/apt/apt.conf.d/50unattended-upgrades

-   name: Create user
    user:
        name: "{{ server_user }}"
        state: present
        shell: /bin/bash
        groups: "{{ server_user_groups }}"

-   name: Add ssh-key for new user (from local file)
    authorized_key:
        user: "{{ server_user }}"
        state: present
        key: "{{ lookup('file', item) }}"
    with_items: "{{ pub_ssh_key_location }}"
    when: pub_ssh_key_location is defined

-   name: Add ssh-keys for all team members (from GitHub)
    authorized_key:
        user: "{{ server_user }}"
        state: present
        key: "https://github.com/{{ item }}.keys"
    with_items: "{{ github_users }}"
    when: github_users is defined

-   name: Create individual user accounts for team members
    user:
        name: "{{ item.user }}"
        state: present
        shell: /bin/bash
        groups: "{{ item.groups | default([]) }}"
        create_home: yes
    loop: "{{ users_to_add }}"
    when: users_to_add is defined

- name: Set ssh keys for regular users from GitHub
  authorized_key:
    user: "{{ item.user }}"
    key: "https://github.com/{{ item.github }}.keys"
    exclusive: no # Behåller andra SSH-nycklar, tar inte bort dem
  loop: "{{ users_to_add }}"
  when: 
      - users_to_add is defined
      - item.github is defined

-   name: Add user to sudoers
    lineinfile:
        dest: /etc/sudoers
        regexp: "{{ server_user }} ALL"
        line: "{{ server_user }} ALL=(ALL) NOPASSWD:ALL"
        state: present
        validate: '/usr/sbin/visudo -cf %s' # kan få fel med line "{{ server_user }} testing"

-   name: Add individual users to sudoers
    lineinfile:
        dest: /etc/sudoers
        regexp: "^{{ item.user }} ALL"
        line: "{{ item.user }} ALL=(ALL) NOPASSWD:ALL"
        state: present
        validate: '/usr/sbin/visudo -cf %s'
    loop: "{{ users_to_add }}"
    when: users_to_add is defined

-   # Backup old SSH config
-   name: Backup existing SSH config
    copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.backup
        remote_src: yes
        mode: '0600'
    ignore_errors: yes

# Copy Modern SSH configuration
-   name: Copy Modern OpenSSH configuration
    copy:
        src: files/sshd_config_modern
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0600'
        validate: '/usr/sbin/sshd -T -f %s'
    notify: restart ssh

# Update AllowUsers with all team members
-   name: Update AllowUsers in SSH config
    lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^AllowUsers"
        line: "AllowUsers {{ server_user }} {{ root_user | default('azureuser') }} {{ users_to_add | map(attribute='user') | join(' ') }}"
        state: present
        validate: '/usr/sbin/sshd -T -f %s'
    when: users_to_add is defined
    notify: restart ssh
-   name: flush handlers to restart SSH
    meta: flush_handlers # we cant do it later because after this we cant ssh as root

    # ignore_errors: yes

-   #name: Remove default user
    #remote_user: "{{ server_user }}"
    #user:
        #name: azureuser
        #state: absent
        #force: yes
        #remove: yes
    # ignore_errors: yes
