name: Security Checks

on:
  push:
    branches: [ "**" ]
    branches: [ "master", "main" ]

permissions:
  contents: read

jobs:
  devsecops:
    name: DevSecOps Pipeline
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Analysis

        run: bandit -r . -x ./ansible,./tests,./.github -ll

      - name: Build Docker image for testing
        run: |
          docker build -f docker/Dockerfile -t microblog:security .


      - name: Run Dockle
        uses: goodwithtech/dockle-action@v0
        with:
          image: microblog:security
          exit-code: 0
          failure-threshold: WARN

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'microblog:security'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'